In [ ]:
#PANDAS
import pandas as pd     

In [ ]:
# (1) dataseries - 1D (2) dataframe - 2D

In [ ]:
ds = pd.Series([4, 7, -5, 3])

print(type(ds))
print(ds)               # default index (0 to N-1)


<class 'pandas.core.series.Series'>
0    4
1    7
2   -5
3    3
dtype: int64


In [ ]:
print(ds.values)
print(ds.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [ ]:
ds = pd.Series([4, 7, -5, 3], index=['b','c','a','d'])
print(ds)

b    4
c    7
a   -5
d    3
dtype: int64


In [ ]:
print(ds['a'])  # returned back a scalar value

-5


In [ ]:
ds['c'] = 10
print(ds)

b     4
c    10
a    -5
d     3
dtype: int64


In [ ]:
x = ds[ ['b', 'd'] ]
print(type(x))
print(x)

<class 'pandas.core.series.Series'>
b    4
d    3
dtype: int64


In [ ]:
#boolean index
#print(ds)

print(ds[[True, False, True, False]])

b    4
a   -5
dtype: int64


In [ ]:
#boolean index

x = ds > 3
print(x)

b     True
c     True
a    False
d    False
dtype: bool


In [ ]:
x = ds[ (ds > 3) ]
print(x)

b     4
c    10
dtype: int64


In [ ]:
#data series : using dictionaries

dc = {'D' : 10, 'C' : -5, 'B' : 10, 'A' : 3}

print(dc)

ds = pd.Series(dc)
print(ds)

{'D': 10, 'C': -5, 'B': 10, 'A': 3}
D    10
C    -5
B    10
A     3
dtype: int64


In [ ]:
print(ds['C'])

-5


In [ ]:
#numeric-indexing

In [ ]:
print(ds[1])     #returns scalar value

-5


In [ ]:
print(ds[1:3])   #returns data-series

C    -5
B    10
dtype: int64


In [ ]:
# NaN = Not a Number
import numpy as np


In [ ]:
ds = pd.Series([4, 3, np.nan, 10])
print(ds)

0     4.0
1     3.0
2     NaN
3    10.0
dtype: float64


In [ ]:
ds.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
ds.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [ ]:
#arithmetic operations between data-series

ds1 = pd.Series([10, 20, 30], index=['b', 'a', 'd'])

ds2 = pd.Series( {'a' : 100, 'b' : 50, 'd' : 30} )

print(ds1)
print(ds2)

ds3 = ds1 + ds2 

print('\n')
print(ds3)

b    10
a    20
d    30
dtype: int64
a    100
b     50
d     30
dtype: int64


a    120
b     60
d     60
dtype: int64


In [ ]:
#data-alignments

ds1 = pd.Series([10, 20, 30], index=['b', 'a', 'c'])

ds2 = pd.Series( {'a' : 100, 'b' : 50, 'd' : 30} )

ds3 = ds1 + ds2 
print(ds3)

a    120.0
b     60.0
c      NaN
d      NaN
dtype: float64


In [ ]:
print(ds1['a'])  #label -> label of row

20


In [ ]:
print(ds1.a)

20


In [ ]:
x = ds1.get('a')
print(x)

20


In [ ]:
print(ds1)

b    10
a    20
c    30
dtype: int64


In [ ]:
ds1['z'] = 99
print(ds1)

#ds1.z = 99 //error

b    10
a    20
c    30
z    99
dtype: int64


In [ ]:
del ds1['z']
print(ds1)

#del ds1.z //error

b    10
a    20
c    30
dtype: int64


In [ ]:
x = np.arange(1, 8)
print(x)

ds = pd.Series(data = x)
print(ds)

[1 2 3 4 5 6 7]
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [ ]:
x = np.arange(1, 8)
print(x)

labels = ['b','l','g','e','a','a','n']

ds = pd.Series(data = x , index = labels)
print(ds)

[1 2 3 4 5 6 7]
b    1
l    2
g    3
e    4
a    5
a    6
n    7
dtype: int64


In [ ]:
print(ds)

b    1
l    2
g    3
e    4
a    5
a    6
n    7
dtype: int64


In [ ]:
x = np.arange(1, 8)
print(x)

labels = ['b','l','g','e','a','a','n']

ds = pd.Series(data = x , index = labels)
ds.name = 'My_DS'
ds.index.name = 'my_index'

print(ds)

[1 2 3 4 5 6 7]
my_index
b    1
l    2
g    3
e    4
a    5
a    6
n    7
Name: My_DS, dtype: int64


In [ ]:
print(ds.name)        #name of data-series
print(ds.index.name)  #name of the index of the data-series


My_DS
my_index


In [ ]:
print(ds)

my_index
b    1
l    2
g    3
e    4
a    5
a    6
n    7
Name: My_DS, dtype: int64


In [ ]:
#Datafarames : collection of one or more dataseries

ds1 = pd.Series([10, 30, 40, 21, 30])

ds2 = pd.Series(['One', 'Two', 'Three', 'Four', 'Five'])

df = pd.DataFrame( {'Col1' : ds1 , 'Col2' : ds2} )

df.index.name = 'my_index_2'
df.columns.name = 'my_columns'

print(df)
print(df.columns.name)


my_columns  Col1   Col2
my_index_2             
0             10    One
1             30    Two
2             40  Three
3             21   Four
4             30   Five
my_columns


In [ ]:
print(df.head(3))

my_columns  Col1   Col2
my_index_2             
0             10    One
1             30    Two
2             40  Three


In [ ]:
print(df.tail(2))

my_columns  Col1  Col2
my_index_2            
3             21  Four
4             30  Five


In [ ]:

data = { 'State' : ['Ohio', 'Ohio', 'Ohio', 'Nebraska',  'Nebraska', 'Nebraska'],
         'Year' : [2000, 2001, 2002, 2001, 2002, 2003],
         'Population' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2] }

df = pd.DataFrame(data)      

print(df)

      State  Year  Population
0      Ohio  2000         1.5
1      Ohio  2001         1.7
2      Ohio  2002         3.6
3  Nebraska  2001         2.4
4  Nebraska  2002         2.9
5  Nebraska  2003         3.2


In [ ]:
df = pd.DataFrame(np.arange(1, 13).reshape(3,4), columns=['One', 'Two', 'Three', 'Four'], index=['A', 'B','C'])

print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
#print(df['A'])  //error

In [ ]:
print(df['One']) # label -> label of the column 

A    1
B    5
C    9
Name: One, dtype: int64


In [ ]:
x = df['One']
print(type(x))

<class 'pandas.core.series.Series'>


In [ ]:
x = df[ ['One'] ]
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
x = df[ ['One' , 'Two'] ]
print(type(x))
print(x)

<class 'pandas.core.frame.DataFrame'>
   One  Two
A    1    2
B    5    6
C    9   10


In [ ]:
print(df.One)

A    1
B    5
C    9
Name: One, dtype: int64


In [ ]:
#print(df.A)  //error

In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
df['Five'] = [10, 20, 30]
print(df)

   One  Two  Three  Four  Five
A    1    2      3     4    10
B    5    6      7     8    20
C    9   10     11    12    30


In [ ]:
df['Six'] = 1
print(df)

   One  Two  Three  Four  Five  Six
A    1    2      3     4    10    1
B    5    6      7     8    20    1
C    9   10     11    12    30    1


In [ ]:
del df['Six']
print(df)

   One  Two  Three  Four  Five
A    1    2      3     4    10
B    5    6      7     8    20
C    9   10     11    12    30


In [ ]:
#df['New_col'] = [1,2]
#print(df)

In [ ]:
ds = pd.Series([1.5, 2.7], index=['A', 'C'])
#print(ds)
df['New_col'] = ds
print(df)

   One  Two  Three  Four  Five  New_col
A    1    2      3     4    10      1.5
B    5    6      7     8    20      NaN
C    9   10     11    12    30      2.7


In [ ]:
data = { 'State' : ['Ohio', 'Ohio', 'Ohio', 'Nebraska',  'Nebraska', 'Nebraska'],
         'Year' : [2000, 2001, 2002, 2001, 2002, 2003],
         'Population' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2] }

df = pd.DataFrame(data)      

print(df)

      State  Year  Population
0      Ohio  2000         1.5
1      Ohio  2001         1.7
2      Ohio  2002         3.6
3  Nebraska  2001         2.4
4  Nebraska  2002         2.9
5  Nebraska  2003         3.2


In [ ]:
x = (df.State == 'Ohio')
print(type(x))
print(x)

<class 'pandas.core.series.Series'>
0     True
1     True
2     True
3    False
4    False
5    False
Name: State, dtype: bool


In [ ]:
df['Ohio_Present'] = (df.State == 'Ohio')
print(df)

      State  Year  Population  Ohio_Present
0      Ohio  2000         1.5          True
1      Ohio  2001         1.7          True
2      Ohio  2002         3.6          True
3  Nebraska  2001         2.4         False
4  Nebraska  2002         2.9         False
5  Nebraska  2003         3.2         False


In [ ]:
del df['Ohio_Present']

In [ ]:
print(df)

      State  Year  Population
0      Ohio  2000         1.5
1      Ohio  2001         1.7
2      Ohio  2002         3.6
3  Nebraska  2001         2.4
4  Nebraska  2002         2.9
5  Nebraska  2003         3.2


In [ ]:
#view (alias) : in-place modification  [vs] copy

In [ ]:
df = pd.DataFrame(np.arange(1, 13).reshape(3,4), columns=['One', 'Two', 'Three', 'Four'], index=['A', 'B','C'])

print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
x = df['Three']   #creates a view/alias name; no new object is created; in-place modification
print(x)

A     3
B     7
C    11
Name: Three, dtype: int64


In [ ]:
x['B'] = 100
print(x)

A      3
B    100
C     11
Name: Three, dtype: int64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6    100     8
C    9   10     11    12


In [ ]:
x = df.Two.copy()         # new object is created
#x = df['Two'].copy()
print(x)

A     2
B     6
C    10
Name: Two, dtype: int64


In [ ]:
x['C'] = 200
print(x)

A      2
B      6
C    200
Name: Two, dtype: int64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6    100     8
C    9   10     11    12


In [ ]:
print(df.T)

       A    B   C
One    1    5   9
Two    2    6  10
Three  3  100  11
Four   4    8  12


In [ ]:
print(df.swapaxes(0, 1) )

       A    B   C
One    1    5   9
Two    2    6  10
Three  3  100  11
Four   4    8  12


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6    100     8
C    9   10     11    12


In [ ]:
print(df.keys())

Index(['One', 'Two', 'Three', 'Four'], dtype='object')


In [ ]:
print(df.columns)

Index(['One', 'Two', 'Three', 'Four'], dtype='object')


In [ ]:
print(df.values)

[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [ ]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')


In [ ]:
#Indexing and Slicing

In [ ]:
ds = pd.Series([4, 7, -5, 3], index=['b','c','a','d'])
print(ds)

print('\n')

df = pd.DataFrame(np.arange(1, 13).reshape(3,4), columns=['One', 'Two', 'Three', 'Four'], index=['A', 'B','C'])
print(df)

b    4
c    7
a   -5
d    3
dtype: int64


   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
#dataseries

print(ds['a'])       # label/index represent rows

print(ds[2])         # numeric-index represent rows


print(ds[2:4])       #row-slicing  (end-value is excluded)

print(ds['c' : 'd'])  #row-slicing (end-value is included)

-5
-5
a   -5
d    3
dtype: int64
c    7
a   -5
d    3
dtype: int64


In [ ]:
#dataframes

print(df['One'])      #label/index represent columns
print('\n')

print(df[1:2])        #numeric-based row-slicing (end-value is excluded)
print('\n')

print(df['A' : 'B'])  #label based row-slicing (end-value is included)


A    1
B    5
C    9
Name: One, dtype: int64


   One  Two  Three  Four
B    5    6      7     8


   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8


In [ ]:
#loc  : label-based (strings)
#iloc : index-based (number)


In [ ]:
print(ds)

b    4
c    7
a   -5
d    3
dtype: int64


In [ ]:
print(ds.loc['a'])
print('\n')
print(ds.loc['c' : 'd'])  #(end value is included)

-5


c    7
a   -5
d    3
dtype: int64


In [ ]:
print(ds.iloc[1])
print('\n')
print(ds.iloc[1:3])    #(end value is excluded)

7


c    7
a   -5
dtype: int64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
print(df.loc['B'])
print('\n')

print(df.loc['B' : 'C'])  #(end value is included)

One      5
Two      6
Three    7
Four     8
Name: B, dtype: int64


   One  Two  Three  Four
B    5    6      7     8
C    9   10     11    12


In [ ]:
print(df.iloc[1])
print('\n')
print(df.iloc[0:2])  #(end value is excluded)

One      5
Two      6
Three    7
Four     8
Name: B, dtype: int64


   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
print(df.loc['B', ['Two', 'Four']]) 

Two     6
Four    8
Name: B, dtype: int64


In [ ]:
print(df.iloc[1, [1, 3]]) 

Two     6
Four    8
Name: B, dtype: int64


In [ ]:
print(df.loc[ ['B' , 'C'], ['Two', 'Four']]) 

   Two  Four
B    6     8
C   10    12


In [ ]:
print(df.loc[ ['B' , 'C'], 'Four' ]) 

B     8
C    12
Name: Four, dtype: int64


In [ ]:
print(df.iloc[ [1 , 2], [1, 3]]) 

   Two  Four
B    6     8
C   10    12


In [ ]:
print(df.iloc[ [1 , 2], 3 ]) 

B     8
C    12
Name: Four, dtype: int64


In [ ]:
print(df.iloc[ [1 , 2],  : ]) 

   One  Two  Three  Four
B    5    6      7     8
C    9   10     11    12


In [ ]:
print(df.loc[:, ['Two', 'Four'] ])

   Two  Four
A    2     4
B    6     8
C   10    12


In [ ]:
print(df.iloc[:, [1, 3] ])

   Two  Four
A    2     4
B    6     8
C   10    12


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
x = df.loc[['A', 'C']]
print(type(x))
print(x)


<class 'pandas.core.frame.DataFrame'>
   One  Two  Three  Four
A    1    2      3     4
C    9   10     11    12


In [ ]:
df.loc[['A', 'C']] [['Two', 'Four']]

Two  Four
A    2     4
C   10    12

In [ ]:
#boolean-indexing

In [ ]:
ds = pd.Series([4, 7, -5, 3], index=['b','c','a','d'])
print(ds)

print('\n')

df = pd.DataFrame(np.arange(1, 13).reshape(3,4), columns=['One', 'Two', 'Three', 'Four'], index=['A', 'B','C'])
print(df)

b    4
c    7
a   -5
d    3
dtype: int64


   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
print(ds[ [True, False, False, True] ] ) 

b    4
d    3
dtype: int64


In [ ]:
x = ds < 4
print(x)

b    False
c    False
a     True
d     True
dtype: bool


In [ ]:
print ( ds[ (ds < 4)  ] ) 

a   -5
d    3
dtype: int64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
print( df[ [False, True, False] ] )  # boolean-indexing : row-wise

   One  Two  Three  Four
B    5    6      7     8


In [ ]:
df.loc[ [False, True, False] , : ]  #loc -> label , iloc -> number

One  Two  Three  Four
B    5    6      7     8

In [ ]:
df.iloc[ [False, True, False] , : ]

One  Two  Three  Four
B    5    6      7     8

In [ ]:
df.loc[ [True, False, True], [True, False, True, False] ]

One  Three
A    1      3
C    9     11

In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
df.Three > 5

A    False
B     True
C     True
Name: Three, dtype: bool

In [ ]:
df[ (df.Three > 5)]

One  Two  Three  Four
B    5    6      7     8
C    9   10     11    12

In [ ]:
#get , at

print(ds)

b    4
c    7
a   -5
d    3
dtype: int64


In [ ]:
ds.get('a')

-5

In [ ]:
ds.at['a']

-5

In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
df.get('One')

A    1
B    5
C    9
Name: One, dtype: int64

In [ ]:
df.at['B', 'Three']

7

In [ ]:
#np.where

In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
x = np.where(df < 6, 0, (df  * 2)) 
print(type(x) )
print(x)

<class 'numpy.ndarray'>
[[ 0  0  0  0]
 [ 0 12 14 16]
 [18 20 22 24]]


In [ ]:
#reindex
print(ds)

b    4
c    7
a   -5
d    3
dtype: int64


In [ ]:
ds1 = ds.reindex(['a','b','c','z', 'd', 'e'])
print(ds1)

a   -5.0
b    4.0
c    7.0
z    NaN
d    3.0
e    NaN
dtype: float64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
df1 = df.reindex(index = ['C','A','B'])
print(df1)

   One  Two  Three  Four
C    9   10     11    12
A    1    2      3     4
B    5    6      7     8


In [ ]:
df2 = df.reindex(index = ['C','A','B'], columns = ['Three','One','Four','Two'])
print(df2)

   Three  One  Four  Two
C     11    9    12   10
A      3    1     4    2
B      7    5     8    6


In [ ]:
#drop

print(ds)

b    4
c    7
a   -5
d    3
dtype: int64


In [ ]:
x = ds.drop('c')
print(x)

b    4
a   -5
d    3
dtype: int64


In [ ]:
x = ds.drop(['c','d'])
print(x)

b    4
a   -5
dtype: int64


In [ ]:
print(df)

   One  Two  Three  Four
A    1    2      3     4
B    5    6      7     8
C    9   10     11    12


In [ ]:
x = df.drop(index=['A', 'C'])
print(x)

   One  Two  Three  Four
B    5    6      7     8


In [ ]:
x = df.drop(['A', 'C'], axis=0)
print(x)

   One  Two  Three  Four
B    5    6      7     8


In [ ]:
x = df.drop(index=['A'], columns = ['Four', 'Two'])
print(x)

   One  Three
B    5      7
C    9     11


In [ ]:
x = df.drop(columns = ['Four', 'Two'])
print(x)

   One  Three
A    1      3
B    5      7
C    9     11


In [ ]:
x = df.drop(['Four', 'Two'], axis=1)
print(x)

   One  Three
A    1      3
B    5      7
C    9     11
