In [1]:
import pandas as pd
import numpy as np

In [ ]:
#stacking - adding data vertically, horizontally

In [7]:
#vertical stacking : stack the rows (vstack, row_stack)

n1 = np.arange(0,10, 2)

n2 = np.arange(5)

print(n1)
print(n2)


print()
#n3 = np.vstack( (n1, n2) )
n3 = np.row_stack( (n1, n2) )
print(n3)

[0 2 4 6 8]
[0 1 2 3 4]

[[0 2 4 6 8]
 [0 1 2 3 4]]


In [14]:
n1 = np.array([ [1,2,3], [4,5,6] ])  #2D

row1 = [7, 8, 9]             #1D
row2 = [10,11,12]          #1D 

n2 = np.vstack( (n1, row1, row2) )
print(n2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
n1 = np.array([ [1,2,3], [4,5,6] ])  #2D
n2 = np.array([ [11,12,13], [14,15,16] ])  #2D
n3 = np.array([ 10, 20, 30])  #1D

n4 = np.vstack( (n1, n2, n3) )

print(n4)



[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]
 [10 20 30]]


In [21]:
#horizontal stacking : stack the columns (hstack, column_stack)

n1 = np.array([ [1,2,3], [4,5,6] ])  #2D
n2 = np.array([ [7] ,[8] ])

n3 = np.hstack( (n1, n2))
print(n3)

[[1 2 3 7]
 [4 5 6 8]]


In [24]:
n1 = np.array([ [1,2,3], [4,5,6] ])  #2D
n2 = np.array([ [7, 9] ,[8, 10] ])   #2D

n3 = np.hstack( (n1, n2))
#n3 = np.column_stack( (n1, n2))
print(n3)

[[ 1  2  3  7  9]
 [ 4  5  6  8 10]]


In [25]:
n1 = np.array([ [1,2,3], [4,5,6], [4,5,6], [4,5,6] ])  #2D
n2 = np.array([ [7] ,[8], [9],[10] ])   #2D

n3 = np.hstack( (n1, n2))
#n3 = np.column_stack( (n1, n2))
print(n3)

[[ 1  2  3  7]
 [ 4  5  6  8]
 [ 4  5  6  9]
 [ 4  5  6 10]]


In [27]:
#insert  (axis=0, axis=1)

n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array([ 7,8,9] )

n3 = np.insert(n1, 1, n2, axis=0)
print(n3)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [33]:
n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array( [7, 8] )

n3 = np.insert(n1, 1, n2, axis=1)
print(n3)

[[1 7 2 3]
 [4 8 5 6]]


In [38]:
#insert, append, concatenate
n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array([[7,8,9]])

n3 = np.append(n1, n2, axis=0)
print(n3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array([[7],[8]])

n3 = np.append(n1, n2, axis=1)
print(n3)

[[1 2 3 7]
 [4 5 6 8]]


In [42]:
n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array([[7,8,9]])

n3 = np.concatenate( (n1, n2) , axis=0)
print(n3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
n1 = np.array([ [1,2,3], [4,5,6] ])
n2 = np.array([[7],[8]])

n3 = np.concatenate( (n1, n2) , axis=1)
print(n3)

[[1 2 3 7]
 [4 5 6 8]]


In [51]:
#split

x = np.arange(12)
print(x)

n = np.split(x, 2)  
print(type(n), len(n))

print(n[0])
print(n[1])
#print(n[2])
#print(n[3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'list'> 2
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]


In [53]:
x = np.arange(12)
n = np.split(x, [1, 3, 9] )
print(type(n), len(n))

print(n[0])
print(n[1])
print(n[2])
print(n[3])

<class 'list'> 4
[0]
[1 2]
[3 4 5 6 7 8]
[ 9 10 11]


In [61]:
x = np.arange(16).reshape(4,4)
print(x)

a = np.hsplit(x, 4)
print()
print(a[0])
print(a[1])
print(a[2])
print(a[3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [66]:
x = np.arange(16).reshape(4,4)
print(x)
print()
a = np.vsplit(x, 4)
print(a[0])
print(a[1])
print(a[2])
print(a[3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
