In [12]:
# imports
import numpy as np


In [13]:
# Vstack: vertical stack
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n2 = np.array([[7, 8, 9], [10, 11, 12]])
n3 = np.array([13, 14, 15])

np.vstack((n1, n2, n3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [14]:
# Horizontal Stacking: hstack

n1 = np.array([[1, 2, 3], [5, 6, 7]])
n2 = np.array([[4], [8]])

np.hstack((n1, n2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Horizontal Stacking: column stack

n1 = np.array([[1, 2, 3], [6, 7, 8]])
n2 = np.array([[4, 5], [8, 9]])

print(np.hstack((n1, n2)))

print()

print(np.column_stack((n1, n2)))


[[1 2 3 4 5]
 [6 7 8 8 9]]

[[1 2 3 4 5]
 [6 7 8 8 9]]


In [16]:
# Stacking as insertion

n1 = np.array([[1, 2, 3], [4, 5, 6]])

# vertical stack
print(np.insert(n1, 1, np.array([7, 8, 9]), axis=0))

# horizontal stack
print(np.insert(n1, 1, np.array([[7, 8]]), axis=1))


[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 7 2 3]
 [4 8 5 6]]


In [21]:
# append
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n2 = np.array([[7, 8, 9]])
n3 = np.array([[7], [8]])

print(np.append(n1, n2, axis=0))

print(np.append(n1, n3, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [24]:
# concatenate
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n2 = np.array([[7, 8, 9]])
n3 = np.array([[7], [8]])

print(np.concatenate((n1, n2), axis=0))

print()
print(print(np.concatenate((n1, n3), axis=1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 7]
 [4 5 6 8]]
None


In [32]:
# split

arr = np.arange(12)

print(np.split(arr, 4))

print(np.split(arr, 3))

print(np.split(arr, [1,3,9]))


arr2 = arr.reshape(3,4)
print(arr2)

print(np.hsplit(arr2, 2))

print(np.vsplit(arr2, 3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0]), array([1, 2]), array([3, 4, 5, 6, 7, 8]), array([ 9, 10, 11])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
